version: '3'
services:
  spark:
    container_name: spark-notebook
#    image: jupyter/pyspark-notebook
    build: .
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    volumes:
      - /home/jesse/data-platform/data-platform/notebooks/:/home/jovyan/
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} 
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
