version: '3.7'

##################################################################
# Minio Object store
##################################################################

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-04-26T01-20-24Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    container_name: minio1
    volumes:
      - ${DATA_LOCATION}/minio/data1-1:/data1
      - ${DATA_LOCATION}/minio/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    container_name: minio2
    volumes:
      - ${DATA_LOCATION}/minio/data2-1:/data1
      - ${DATA_LOCATION}/minio/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    container_name: minio3
    volumes:
      - ${DATA_LOCATION}/minio/data3-1:/data1
      - ${DATA_LOCATION}/minio/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    container_name: minio4
    volumes:
      - ${DATA_LOCATION}/minio/data4-1:/data1
      - ${DATA_LOCATION}/minio/data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    container_name: minio_nginx
    volumes:
      - ./minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4


##################################################################
# Spark notebook
##################################################################

  spark:
    container_name: spark-notebook
#    image: jupyter/pyspark-notebook
    build: spark-notebook/
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    volumes:
      - /home/jesse/data-platform/data-platform/notebooks/:/home/jovyan/
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} 
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

##################################################################
# Hive metastore
##################################################################

  hive:
    build: metastore/
    entrypoint: /init-hive.sh
    ports:
      - "9083:9083"
      - "10000:10000"
    links:
      - "postgres:postgres"

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    ports:
      - '5432:5432'
    #volumes:
    #  - ${DATA_LOCATION}/postgres:/var/lib/postgresql/data/pgd