version: '3.5'
services:
  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    volumes:
      #- /home/jesse/data/dremio/data:/var/lib/dremio
      - dremio-data:/var/lib/dremio
      - ./localFiles:/localFiles
      #- /home/jesse/data/dremio/data:/opt/dremio/data
      - dremio-data:/opt/dremio/data
    ports:
      - "9047:9047"
      - "31010:31010"
      - "45678:45678"

volumes:
  dremio-data: